import { execFile } from "node:child_process";
import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { moduleFiles, workspaceModules } from "./module-files.ts";

const STRICT_CONFIG = "tsconfig.strict.json";
const SOURCE = /\.[cm]?tsx?$/;
const TEST = /\.test\.[cm]?tsx?$/;

export interface ModuleTypecheckResult {
	ok: boolean;
	output: string;
}

/** A module opts in by adding tsconfig.strict.json extending the shared strict config. */
export function strictModules(root: string): string[] {
	return workspaceModules(path.resolve(root)).filter((directory) => existsSync(path.join(directory, STRICT_CONFIG)));
}

function compile(root: string, config: string): Promise<ModuleTypecheckResult> {
	return new Promise((resolve) => {
		execFile(
			process.execPath,
			[path.join(root, "node_modules/typescript/bin/tsc"), "--project", config, "--pretty", "false"],
			{ cwd: root, maxBuffer: 16 * 1024 * 1024 },
			(error, stdout, stderr) => {
				const compilerDiagnostics = stdout + stderr;
				const failedToRun = error && (typeof error.code !== "number" || ![1, 2].includes(error.code));
				resolve({
					ok: !error,
					output: failedToRun
						? `${compilerDiagnostics}\n${error.message}`
						: compilerDiagnostics || error?.message || "",
				});
			},
		);
	});
}

function inside(directory: string, file: string): boolean {
	const relative = path.relative(directory, file);
	return (
		relative === "" || (!relative.startsWith(`..${path.sep}`) && relative !== ".." && !path.isAbsolute(relative))
	);
}

/**
 * Keep the dependency sources in the strict program so their inferred nullable
 * types reach consumers. Only strict diagnostics owned by the selected module
 * are gated here; the preceding baseline pass gates ALL dependency diagnostics.
 * Declaration emission under strict:false would erase inferred nullability.
 */
function scopedStrictResult(result: ModuleTypecheckResult, root: string, directory: string) {
	const diagnostics = result.output
		.trim()
		.split(/\r?\n(?=\S)/)
		.filter(Boolean);
	const deferred: string[] = [];
	const failures: string[] = [];
	for (const diagnostic of diagnostics) {
		const match = /^(.+)\(\d+,\d+\): error TS\d+:/.exec(diagnostic);
		const file = match ? path.resolve(root, match[1]) : undefined;
		// Global errors, compiler failures, and diagnostics outside workspace
		// module dependencies must never disappear through scoping.
		if (file && inside(path.join(root, "modules"), file) && !inside(directory, file)) deferred.push(diagnostic);
		else failures.push(diagnostic);
	}
	return {
		ok: failures.length === 0 && (result.ok || deferred.length > 0),
		output: failures.join("\n"),
		deferred: deferred.length,
	};
}

/** Check complete selected modules, accepting absolute or repository-relative directories. */
export async function typecheckModules({
	root,
	modules,
}: {
	root: string;
	modules: string[];
}): Promise<ModuleTypecheckResult> {
	root = path.resolve(root);
	const temporary = mkdtempSync(path.join(tmpdir(), "spicetify-module-types-"));
	const output: string[] = [];
	let ok = true;
	try {
		const directories = workspaceModules(root);
		for (const selected of modules) {
			const directory = path.resolve(root, selected);
			const label = path.relative(root, directory);
			if (!inside(root, directory) || !existsSync(path.join(directory, "metadata.json"))) {
				throw new Error(`Not a workspace module: ${selected}`);
			}
			const codegen = path.join(root, "modules/stdlib/src/webpack/CODEGEN.ts");
			const sources = moduleFiles(directory).filter((file) => SOURCE.test(file) && file !== codegen);
			const runtime = sources.filter((file) => !TEST.test(file) && path.basename(file) !== "test-setup.mts");
			const tests = sources.filter((file) => TEST.test(file) || path.basename(file) === "test-setup.mts");
			if (!sources.length) {
				output.push(`${label}: no TypeScript sources`);
				continue;
			}
			const strict = existsSync(path.join(directory, STRICT_CONFIG));
			const globals = ["spicetify.d.ts", "platform.d.ts", "remote-modules.d.ts", "modules/stdlib/src/chunks.d.ts"]
				.map((file) => path.join(root, file))
				.filter(existsSync);
			// Classmaps are generated by stitch. Use one declaration per program,
			// including when the selected module itself does not reference MAP.
			const classmap = [directory, ...directories]
				.map((module) => path.join(module, "classmap.d.ts"))
				.find(existsSync);
			if (classmap) globals.push(classmap);
			for (const [environment, files] of [
				["client", runtime],
				["tests", tests],
			] as const) {
				if (!files.length) continue;
				for (const mode of strict ? ["baseline", "strict"] : ["baseline"]) {
					const config = path.join(temporary, "tsconfig.json");
					writeFileSync(
						config,
						JSON.stringify({
							extends:
								mode === "strict"
									? path.join(directory, STRICT_CONFIG)
									: path.join(root, "tsconfig.module.json"),
							compilerOptions: {
								noEmit: true,
								noCheck: false,
								strict: mode === "strict",
								...(mode === "strict"
									? {
											alwaysStrict: true,
											noImplicitAny: true,
											noImplicitThis: true,
											strictBindCallApply: true,
											strictBuiltinIteratorReturn: true,
											strictFunctionTypes: true,
											strictNullChecks: true,
											strictPropertyInitialization: true,
											useUnknownInCatchVariables: true,
										}
									: {}),
								types: environment === "tests" ? ["node"] : [],
								typeRoots: [path.join(root, "node_modules/@types")],
							},
							files: [...globals, ...files.filter((file) => path.basename(file) !== "classmap.d.ts")],
							include: [],
							exclude: [],
						}),
					);
					const result = await compile(root, config);
					const checked = mode === "strict" ? scopedStrictResult(result, root, directory) : result;
					ok &&= checked.ok;
					output.push(`${label} (${environment}, ${mode}): ${checked.ok ? "passed" : "failed"}`);
					if (checked.output) output.push(checked.output.trim());
					if ("deferred" in checked && checked.deferred) {
						output.push(
							`  ${checked.deferred} strict dependency diagnostics deferred; dependencies passed the baseline gate, not strict.`,
						);
					}
					if (!checked.ok) break;
				}
			}
		}
		return { ok, output: output.join("\n") };
	} finally {
		rmSync(temporary, { recursive: true, force: true });
	}
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const args = process.argv.slice(2);
	const root = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
	if (
		args.length === 0 ||
		(args.some((arg) => arg.startsWith("--")) && !(args.length === 1 && args[0] === "--strict"))
	) {
		console.error("Usage: node scripts/module-typecheck.ts --strict | modules/<name> [...]");
		process.exitCode = 1;
	} else {
		const result = await typecheckModules({ root, modules: args[0] === "--strict" ? strictModules(root) : args });
		console.log(result.output || "No modules have opted into strict checking.");
		if (!result.ok) process.exitCode = 1;
	}
}
