import { execFile } from "node:child_process";
import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { moduleFiles, workspaceModules } from "./module-files.ts";

const SOURCE = /\.[cm]?tsx?$/;
const TEST = /\.test\.[cm]?tsx?$/;

export interface ModuleTypecheckResult {
	ok: boolean;
	output: string;
}

function compile(root: string, config: string): Promise<ModuleTypecheckResult> {
	return new Promise((resolve) => {
		execFile(
			process.execPath,
			[path.join(root, "node_modules/typescript/bin/tsc"), "--project", config, "--pretty", "false"],
			{ cwd: root, maxBuffer: 16 * 1024 * 1024 },
			(error, stdout, stderr) => {
				const compilerDiagnostics = stdout + stderr;
				const failedToRun = error && (typeof error.code !== "number" || ![1, 2].includes(error.code));
				resolve({
					ok: !error,
					output: failedToRun
						? `${compilerDiagnostics}\n${error.message}`
						: compilerDiagnostics || error?.message || "",
				});
			},
		);
	});
}

function inside(directory: string, file: string): boolean {
	const relative = path.relative(directory, file);
	return (
		relative === "" || (!relative.startsWith(`..${path.sep}`) && relative !== ".." && !path.isAbsolute(relative))
	);
}

/** Check complete selected modules, accepting absolute or repository-relative directories. */
export async function typecheckModules({
	root,
	modules,
}: {
	root: string;
	modules: string[];
}): Promise<ModuleTypecheckResult> {
	root = path.resolve(root);
	const temporary = mkdtempSync(path.join(tmpdir(), "spicetify-module-types-"));
	const output: string[] = [];
	let ok = true;
	try {
		const directories = workspaceModules(root);
		for (const selected of modules) {
			const directory = path.resolve(root, selected);
			const label = path.relative(root, directory);
			if (!inside(root, directory) || !existsSync(path.join(directory, "metadata.json"))) {
				throw new Error(`Not a workspace module: ${selected}`);
			}
			const codegen = path.join(root, "modules/stdlib/src/webpack/CODEGEN.ts");
			const sources = moduleFiles(directory).filter((file) => SOURCE.test(file) && file !== codegen);
			const runtime = sources.filter((file) => !TEST.test(file) && path.basename(file) !== "test-setup.mts");
			const tests = sources.filter((file) => TEST.test(file) || path.basename(file) === "test-setup.mts");
			if (!sources.length) {
				output.push(`${label}: no TypeScript sources`);
				continue;
			}
			const globals = ["spicetify.d.ts", "platform.d.ts", "remote-modules.d.ts", "modules/stdlib/src/chunks.d.ts"]
				.map((file) => path.join(root, file))
				.filter(existsSync);
			// Classmaps are generated by stitch. Use one declaration per program,
			// including when the selected module itself does not reference MAP.
			const classmap = [directory, ...directories]
				.map((module) => path.join(module, "classmap.d.ts"))
				.find(existsSync);
			if (classmap) globals.push(classmap);
			for (const [environment, files] of [
				["client", runtime],
				["tests", tests],
			] as const) {
				if (!files.length) continue;
				const config = path.join(temporary, "tsconfig.json");
				writeFileSync(
					config,
					JSON.stringify({
						extends: path.join(root, "tsconfig.module.json"),
						compilerOptions: {
							noEmit: true,
							noCheck: false,
							strict: true,
							alwaysStrict: true,
							noImplicitAny: true,
							noImplicitThis: true,
							strictBindCallApply: true,
							strictBuiltinIteratorReturn: true,
							strictFunctionTypes: true,
							strictNullChecks: true,
							strictPropertyInitialization: true,
							useUnknownInCatchVariables: true,
							types: environment === "tests" ? ["node"] : [],
							typeRoots: [path.join(root, "node_modules/@types")],
						},
						files: [...globals, ...files.filter((file) => path.basename(file) !== "classmap.d.ts")],
						include: [],
						exclude: [],
					}),
				);
				const result = await compile(root, config);
				ok &&= result.ok;
				output.push(`${label} (${environment}, strict): ${result.ok ? "passed" : "failed"}`);
				if (result.output) output.push(result.output.trim());
			}
		}
		return { ok, output: output.join("\n") };
	} finally {
		rmSync(temporary, { recursive: true, force: true });
	}
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const args = process.argv.slice(2);
	const root = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
	if (
		args.length === 0 ||
		(args.some((arg) => arg.startsWith("--")) && !(args.length === 1 && args[0] === "--all"))
	) {
		console.error("Usage: node scripts/module-typecheck.ts --all | modules/<name> [...]");
		process.exitCode = 1;
	} else {
		const result = await typecheckModules({ root, modules: args[0] === "--all" ? workspaceModules(root) : args });
		console.log(result.output || "No workspace modules found.");
		if (!result.ok) process.exitCode = 1;
	}
}
