name: Publish

on:
   push:
      tags:
         - "*"

jobs:
   publish:
      name: Publish
      runs-on: ubuntu-latest

      permissions:
         contents: write

      steps:
         -  name: Clone repository
            uses: actions/checkout@v4

         -  name: Clone classmaps
            uses: actions/checkout@v4
            with:
               repository: spicetify/classmaps
               path: classmaps

         -  name: Setup Node
            uses: actions/setup-node@v6
            with:
               node-version: "24"
               cache: npm

         -  name: Install dependencies
            run: npm ci

         -  name: Build modules
            run: node scripts/stitch.mjs

         -  name: Publish
            uses: ./.github/actions/release
